import{createClient}from'https://esm.sh/@supabase/supabase-js@2.57.4';
const sb=createClient('https://xiptoqvgpmxvoqrqlrbb.supabase.co','sb_publishable_3bhZUNlWY6ArDy0T72d0Yg_6bVY_Aij');
const norm=p=>p==='/'||p==='/index.html'?'/':p.endsWith('/index.html')?p.slice(0,-10):p;
const safeUrl=v=>{if(!v)return null;try{if(v.startsWith('/'))return v;const u=new URL(v,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const safeColor=(v,fallback)=>/^#[0-9a-f]{6}$/i.test(v||'')?v:fallback;
const editableSelector='main h1,main h2,main h3,main h4,main p,main li,main a,main img,footer p,footer span,footer strong,footer img';
const heroSelector='.hero,.pagehero,.pageHero,.projectHero,.serviceHero,.locationHero,[data-site-hero]';
function editableNodes(){return [...document.querySelectorAll(editableSelector)].filter(el=>!el.closest('script,style,form')&&!el.closest(heroSelector)&&!el.matches('[data-cms-ignore]'))}
function keyOf(el){if(el.dataset.cmsKey)return el.dataset.cmsKey;const parts=[];let n=el;while(n&&n.nodeType===1){if(n.id){parts.unshift('#'+CSS.escape(n.id));break}let seg=n.tagName.toLowerCase();const parent=n.parentElement;if(parent){const same=[...parent.children].filter(x=>x.tagName===n.tagName);if(same.length>1)seg+=`:nth-of-type(${same.indexOf(n)+1})`}parts.unshift(seg);if(n.matches('main,footer'))break;n=parent}return parts.join('>')}
function sections(){const main=document.querySelector('main');if(!main)return[];let list=[...main.children].filter(el=>el.nodeType===1&&!el.matches(heroSelector)&&!el.matches('[data-cms-ignore]'));if(list.length<2)list=[...main.querySelectorAll(':scope > section')].filter(el=>!el.matches(heroSelector));return list.map((el,i)=>({el,key:el.dataset.cmsSection||keyOf(el),i}))}
function applySections(list){if(!Array.isArray(list)||!list.length)return;const current=sections(),map=new Map(current.map(x=>[x.key,x.el]));for(const o of list){const el=map.get(o.key)||current[o.i]?.el;if(el)el.style.display=o.hidden?'none':''}const ordered=list.map(o=>map.get(o.key)||current[o.i]?.el).filter(Boolean);if(ordered.length){const parent=ordered[0].parentElement;if(parent&&ordered.every(el=>el.parentElement===parent))ordered.forEach(el=>parent.appendChild(el))}}
function applyOverrides(list){if(!Array.isArray(list))return;const nodes=editableNodes(),byKey=new Map(nodes.map((el,i)=>[keyOf(el),{el,i}]));for(const o of list){let el=o.key?byKey.get(o.key)?.el:null;if(!el&&Number.isInteger(o.i))el=nodes[o.i];if(!el)continue;if(typeof o.text==='string'&&el.tagName!=='IMG')el.textContent=o.text;if(el.tagName==='A'&&o.href){const u=safeUrl(o.href);if(u)el.setAttribute('href',u)}if(el.tagName==='IMG'&&o.src){const u=safeUrl(o.src);if(u)el.setAttribute('src',u)}}}
function addAssessmentCTA(){if(location.pathname==='/assessment.html'||location.pathname==='/assessment/'||document.querySelector('[data-global-assessment-cta]'))return;const main=document.querySelector('main');if(!main)return;const section=document.createElement('section');section.className='darkband';section.dataset.globalAssessmentCta='true';section.dataset.cmsIgnore='true';section.innerHTML='<div class="wrap"><div class="split"><div><div class="kicker">Free Canopy Health Assessment</div><h2>Know the condition of your canopy before it becomes an emergency.</h2><p>Send us your location, concerns and current photos. We’ll start by reviewing the condition, priorities and appropriate next step—not just the first visible problem.</p><p class="fine">For one location or an entire canopy portfolio.</p></div><div><a class="btn" href="/assessment.html?type=health&utm_source=website&utm_medium=internal&utm_campaign=canopy_health_assessment">Request Your Free Assessment →</a></div></div></div>';main.appendChild(section);let sticky=document.querySelector('.stickyLead');if(sticky){sticky.textContent='Free Canopy Assessment →';sticky.href='/assessment.html?type=health&utm_source=website&utm_medium=sticky&utm_campaign=canopy_health_assessment'}}
try{const path=norm(location.pathname);const[g,p]=await Promise.all([sb.from('website_visual_settings').select('*').eq('id',1).single(),sb.from('website_pages').select('*').eq('path',path).maybeSingle()]);const s=g.data||{},x=p.data||{},accent=safeColor(s.accent_color,'#171718');document.documentElement.style.setProperty('--website-accent',accent);if(x.page_title)document.title=x.page_title;if(x.meta_description){let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m)}m.content=x.meta_description}const header=document.querySelector('header');if(header&&s.header_background)header.style.background=safeColor(s.header_background,'#0a0a0b');const brand=document.querySelector('.brand'),logo=safeUrl(s.logo_url);if(brand&&logo){brand.style.backgroundImage=`url("${logo}")`;brand.style.backgroundSize='contain';brand.style.backgroundRepeat='no-repeat';brand.style.backgroundPosition='left center';brand.setAttribute('aria-label','Lake James Canopies')}const hero=document.querySelector(heroSelector);if(hero){const image=safeUrl(x.hero_image_url);if(image){const raw=Number(s.hero_overlay),o=Math.max(0,Math.min(95,Number.isFinite(raw)?raw:72))/100;hero.style.backgroundImage=`linear-gradient(90deg,rgba(0,0,0,${Math.min(.95,o+.12)}),rgba(0,0,0,${Math.max(0,o-.25)})),url("${image}")`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center'}const eyebrow=hero.querySelector('.eyebrow,.kicker,[data-hero-eyebrow]'),h1=hero.querySelector('h1,[data-hero-headline]');let para=hero.querySelector('[data-hero-subheadline]');if(!para&&h1){let n=h1.nextElementSibling;while(n&&!para){if(n.matches?.('p'))para=n;if(n.matches?.('div,section,article'))break;n=n.nextElementSibling}}const btn=hero.querySelector('a.btn,a.button,[data-hero-cta]');if(eyebrow&&x.hero_eyebrow)eyebrow.textContent=x.hero_eyebrow;if(h1&&x.hero_headline)h1.textContent=x.hero_headline;if(para&&x.hero_subheadline)para.textContent=x.hero_subheadline;if(btn){btn.style.background=accent;btn.style.color='#fff';if(x.cta_text)btn.textContent=x.cta_text;const href=safeUrl(x.cta_href);if(href)btn.href=href}}applyOverrides(x.content_overrides);applySections(x.section_overrides)}catch(e){console.warn('Site manager unavailable; using built-in page content.',e)}finally{addAssessmentCTA()}